name: jao-delivery
version: 1.0.0
github: "UnBParadigmas2022-1/2022.1_G5_Funcional_JaoDelivery"
license: BSD3
author: "Author Group five 2022.1"
maintainer: "jonathan.jb.oliveira@gmail.com"
copyright: "2022 Author Group five of paradgimas de programação subject 2022.1"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/jao-delivery#readme>

dependencies:
  - base >= 4.7 && < 5
  - ansi-terminal
  - deepseq
  - directory
  - split >=0.2 && <0.3
  - MissingH
  - text-icu >= 0.7.0.1 && < 1
  - text

library:
  source-dirs: src

executables:
  jao-delivery-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - jao-delivery

tests:
  jao-delivery-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - jao-delivery
